"""The master list of IceCube institutions and their details.

More or less,
 a more structured JSON file (or less structured MongoDB)

NOTE: Keep things simple here. Avoid non-basic imports,

      so file can be imported by 3rd parties independently.
"""

INSTITUTIONS = {
    "Aachen": {
        "has_mou": "true",
        "name": "RWTH Aachen University",
        "abbreviation": "RWTH",
        "is_US": "false",
    },
    "AcademiaSinica": {
        "has_mou": "true",
        "name": "Academia Sinica",
        "abbreviation": "AS",
        "is_US": "false",
    },
    "Adelaide": {
        "has_mou": "true",
        "name": "University of Adelaide",
        "abbreviation": "ADELAIDE",
        "is_US": "false",
    },
    "Alabama": {
        "has_mou": "true",
        "name": "University of Alabama",
        "abbreviation": "UA",
        "is_US": "true",
    },
    "Alaska-Anchorage": {
        "has_mou": "true",
        "name": "University of Alaska Anchorage",
        "abbreviation": "UAA",
        "is_US": "true",
    },
    "Alberta": {
        "has_mou": "false",
        "name": "University of Alberta",
        "abbreviation": "ALBERTA",
        "is_US": "false",
    },
    "Barbados": {
        "has_mou": "false",
        "name": "University of the West Indies",
        "abbreviation": "BARBADOS",
        "is_US": "false",
    },
    "Berlin": {
        "has_mou": "true",
        "name": "Humboldt-Universität zu Berlin",
        "abbreviation": "HUMBOLDT",
        "is_US": "false",
    },
    "Bochum": {
        "has_mou": "true",
        "name": "Ruhr-Universität Bochum",
        "abbreviation": "BOCHUM",
        "is_US": "false",
    },
    "Bonn": {
        "has_mou": "false",
        "name": "Universität Bonn",
        "abbreviation": "BONN",
        "is_US": "false",
    },
    "Brussels-ULB": {
        "has_mou": "false",
        "name": "Université Libre de Bruxelles",
        "abbreviation": "ULB",
        "is_US": "false",
    },
    "Brussels-VUB": {
        "has_mou": "false",
        "name": "Vrije Universiteit Brussel (VUB)",
        "abbreviation": "VUB",
        "is_US": "false",
    },
    "Canterbury": {
        "has_mou": "true",
        "name": "University of Canterbury",
        "abbreviation": "UC",
        "is_US": "false",
    },
    "Chiba": {
        "has_mou": "true",
        "name": "Chiba University",
        "abbreviation": "CHIBA",
        "is_US": "false",
    },
    "Chicago": {
        "has_mou": "true",
        "name": "University of Chicago",
        "abbreviation": "UCHICAGO",
        "is_US": "true",
    },
    "Clark-Atlanta": {
        "has_mou": "true",
        "name": "Clark-Atlanta University",
        "abbreviation": "CAU",
        "is_US": "true",
    },
    "Columbia": {
        "has_mou": "true",
        "name": "Columbia University",
        "abbreviation": "COLUMBIA",
        "is_US": "true",
    },
    "Copenhagen": {
        "has_mou": "true",
        "name": "University of Copenhagen",
        "abbreviation": "NBI",
        "is_US": "false",
    },
    "DESY": {
        "has_mou": "false",
        "name": "DESY",
        "abbreviation": "DESY",
        "is_US": "false",
    },
    "Delaware": {
        "has_mou": "true",
        "name": "University of Delaware",
        "abbreviation": "UD",
        "is_US": "true",
    },
    "Dortmund": {
        "has_mou": "false",
        "name": "TU Dortmund University",
        "abbreviation": "DTMND",
        "is_US": "false",
    },
    "Drexel": {
        "has_mou": "true",
        "name": "Drexel University",
        "abbreviation": "DREXEL",
        "is_US": "true",
    },
    "Erlangen": {
        "has_mou": "true",
        "name": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
        "abbreviation": "ERLANGEN",
        "is_US": "false",
    },
    "GaTech": {
        "has_mou": "true",
        "name": "Georgia Institute of Technology",
        "abbreviation": "GTECH",
        "is_US": "true",
    },
    "Geneva": {
        "has_mou": "false",
        "name": "Université de Genève",
        "abbreviation": "DPNC",
        "is_US": "false",
    },
    "Gent": {
        "has_mou": "true",
        "name": "University of Gent",
        "abbreviation": "GENT",
        "is_US": "false",
    },
    "Harvard": {
        "has_mou": "true",
        "name": "Harvard University",
        "abbreviation": "HARVARD",
        "is_US": "true",
    },
    "Heidelberg": {
        "has_mou": "false",
        "name": "Max-Planck-Institut für Kernphysik",
        "abbreviation": "PLANCK",
        "is_US": "false",
    },
    "Kansas": {
        "has_mou": "true",
        "name": "University of Kansas",
        "abbreviation": "KU",
        "is_US": "true",
    },
    "Karlsruhe": {
        "has_mou": "true",
        "name": "Karlsruhe Institute of Technology",
        "abbreviation": "KIT",
        "is_US": "false",
    },
    "KingsCollege": {
        "has_mou": "true",
        "name": "King's College London",
        "abbreviation": "KCL",
        "is_US": "false",
    },
    "LBNL": {
        "has_mou": "true",
        "name": "Lawrence Berkeley National Laboratory",
        "abbreviation": "LBNL",
        "is_US": "true",
    },
    "Lausanne": {
        "has_mou": "false",
        "name": "École Polytechnique Fédérale",
        "abbreviation": "EPFL",
        "is_US": "false",
    },
    "Loyola": {
        "has_mou": "true",
        "name": "Loyola University Chicago",
        "abbreviation": "LOYOLA",
        "is_US": "true",
    },
    "MIT": {
        "has_mou": "false",
        "name": "Massachusetts Institute of Technology",
        "abbreviation": "MIT",
        "is_US": "true",
    },
    "Mainz": {
        "has_mou": "true",
        "name": "University of Mainz",
        "abbreviation": "MAINZ",
        "is_US": "false",
    },
    "Manchester": {
        "has_mou": "true",
        "name": "University of Manchester",
        "abbreviation": "UOM",
        "is_US": "false",
    },
    "Marquette": {
        "has_mou": "true",
        "name": "Marquette University",
        "abbreviation": "MARQUETTE",
        "is_US": "true",
    },
    "Maryland": {
        "has_mou": "true",
        "name": "University of Maryland",
        "abbreviation": "UMD",
        "is_US": "true",
    },
    "Mephi": {
        "has_mou": "true",
        "name": "Moscow Engineering Physics Institute",
        "abbreviation": "MEPHI",
        "is_US": "false",
    },
    "Mercer": {
        "has_mou": "true",
        "name": "Mercer University",
        "abbreviation": "MERCER",
        "is_US": "true",
    },
    "Michigan-State": {
        "has_mou": "true",
        "name": "Michigan State University",
        "abbreviation": "MSU",
        "is_US": "true",
    },
    "Mons": {
        "has_mou": "false",
        "name": "Université de Mons",
        "abbreviation": "MONS",
        "is_US": "false",
    },
    "Munich": {
        "has_mou": "true",
        "name": "Technische Universität München",
        "abbreviation": "TUM",
        "is_US": "false",
    },
    "Munster": {
        "has_mou": "true",
        "name": "Universität Münster",
        "abbreviation": "MÜNSTER",
        "is_US": "false",
    },
    "Nebraska": {
        "has_mou": "true",
        "name": "University of Nebraska–Lincoln",
        "abbreviation": "UNL",
        "is_US": "true",
    },
    "NotreDame": {
        "has_mou": "true",
        "name": "Notre Dame",
        "abbreviation": "ND",
        "is_US": "true",
    },
    "Ohio-State": {
        "has_mou": "true",
        "name": "Ohio State University",
        "abbreviation": "OSU",
        "is_US": "true",
    },
    "Oxford": {
        "has_mou": "true",
        "name": "University of Oxford",
        "abbreviation": "UOX",
        "is_US": "false",
    },
    "Padova": {
        "has_mou": "true",
        "name": "Università Degli Studi di Padova",
        "abbreviation": "UNIPD",
        "is_US": "false",
    },
    "Penn-State": {
        "has_mou": "true",
        "name": "Pennsylvania State University",
        "abbreviation": "PSU",
        "is_US": "true",
    },
    "QMLondon": {
        "has_mou": "true",
        "name": "Queen Mary University of London",
        "abbreviation": "QMLONDON",
        "is_US": "false",
    },
    "Queens": {
        "has_mou": "true",
        "name": "Queen's University",
        "abbreviation": "QUEEN'S",
        "is_US": "false",
    },
    "Rochester": {
        "has_mou": "true",
        "name": "University of Rochester",
        "abbreviation": "ROCHESTER",
        "is_US": "true",
    },
    "SD-Mines-Tech": {
        "has_mou": "true",
        "name": "South Dakota School of Mines and Technology",
        "abbreviation": "SDSMT",
        "is_US": "true",
    },
    "SNOLAB": {
        "has_mou": "false",
        "name": "SNOLAB",
        "abbreviation": "SNOLAB",
        "is_US": "false",
    },
    "Southern": {
        "has_mou": "true",
        "name": "Southern University",
        "abbreviation": "SUBR",
        "is_US": "true",
    },
    "Stockholm": {
        "has_mou": "true",
        "name": "Stockholm University",
        "abbreviation": "SU",
        "is_US": "false",
    },
    "Stony-Brook": {
        "has_mou": "true",
        "name": "Stony Brook University",
        "abbreviation": "SBU",
        "is_US": "true",
    },
    "Sungkyunkwan": {
        "has_mou": "true",
        "name": "Sungkyunkwan University",
        "abbreviation": "SKKU",
        "is_US": "false",
    },
    "TDLeeInstitute": {
        "has_mou": "false",
        "name": "Shanghai Jiao Tong University",
        "abbreviation": "TDInstitute",
        "is_US": "false",
    },
    "Texas-Arlington": {
        "has_mou": "true",
        "name": "University of Texas at Arlington",
        "abbreviation": "UTA",
        "is_US": "true",
    },
    "Tokyo": {
        "has_mou": "false",
        "name": "University of Tokyo",
        "abbreviation": "TOKYO",
        "is_US": "false",
    },
    "Toronto": {
        "has_mou": "false",
        "name": "University of Toronto",
        "abbreviation": "TORONTO",
        "is_US": "false",
    },
    "UC-Berkeley": {
        "has_mou": "false",
        "name": "University of California, Berkeley",
        "abbreviation": "UCB",
        "is_US": "true",
    },
    "UC-Irvine": {
        "has_mou": "true",
        "name": "University of California, Irvine",
        "abbreviation": "UCI",
        "is_US": "true",
    },
    "UCLA": {
        "has_mou": "true",
        "name": "UCLA",
        "abbreviation": "UCLA",
        "is_US": "true",
    },
    "UCLouvain": {
        "has_mou": "true",
        "name": "Université catholique de Louvain",
        "abbreviation": "UCLOUVAIN",
        "is_US": "false",
    },
    "UW-Madison": {
        "has_mou": "true",
        "name": "University of Wisconsin–Madison",
        "abbreviation": "UW",
        "is_US": "true",
    },
    "UW-River-Falls": {
        "has_mou": "true",
        "name": "University of Wisconsin, River Falls",
        "abbreviation": "UWRF",
        "is_US": "true",
    },
    "Uppsala": {
        "has_mou": "true",
        "name": "Uppsala University",
        "abbreviation": "UU",
        "is_US": "false",
    },
    "Utah": {
        "has_mou": "true",
        "name": "University of Utah",
        "abbreviation": "UTAH",
        "is_US": "true",
    },
    "Washington": {
        "has_mou": "false",
        "name": "University of Washington",
        "abbreviation": "UWa",
        "is_US": "true",
    },
    "Wuppertal": {
        "has_mou": "true",
        "name": "University of Wuppertal",
        "abbreviation": "WUPPERTAL",
        "is_US": "false",
    },
    "Yale": {
        "has_mou": "true",
        "name": "Yale University",
        "abbreviation": "YALE",
        "is_US": "true",
    },
}
