version: 2.1

jobs:

  unit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          python3 -m virtualenv -p python3 env && . env/bin/activate && pip install --upgrade pip
          curl https://raw.githubusercontent.com/WIPACrepo/keycloak-rest-services/master/keycloak_setup/institution_list.py > rest_server/databases/institution_list.py
          pip install -r rest_server/requirements.txt -r web_app/requirements.txt -r requirements-dev.txt
          pytest -vvv --mypy --flake8 tests/unit

  integrate:
    docker:
      - image: circleci/python:3.8
      - image: circleci/mongo:3.7.9-ram
      - image: wipac/token-service:latest
        environment:
          port: 8888
          auth_secret: secret
        command: [python, test_server.py]
    steps:
      - checkout
      - run:
          command: |
            python3 -m virtualenv -p python3 env_rest && . env_rest/bin/activate && pip install --upgrade pip
            curl https://raw.githubusercontent.com/WIPACrepo/keycloak-rest-services/master/keycloak_setup/institution_list.py > rest_server/databases/institution_list.py
            pip install -r rest_server/requirements.txt
            python3 -m rest_server
          background: true
      - run: |
            python3 -m virtualenv -p python3 env_web && . env_web/bin/activate && pip install --upgrade pip
            sleep 30
            pip install -r rest_server/requirements.txt -r web_app/requirements.txt -r requirements-dev.txt
            pytest -vvv tests/integration

  docker_deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
        environment:
          IMAGE_NAME: wipac/mou-dashboard-services
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
      - run: |
          docker build -t $IMAGE_NAME:$TAG .
      - run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
          docker push $IMAGE_NAME:$TAG

  docker_test_build:
    docker:
      - image: circleci/buildpack-deps:stretch
        environment:
          IMAGE_NAME: wipac/mou-dashboard-services
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
      - run: |
          docker build -t $IMAGE_NAME:$TAG .

workflows:
  build_and_test:
    jobs:
      - unit
      - integrate
      - docker_test_build:
          context: docker
          requires:
            - unit
            - integrate
          filters:
            branches:
              ignore: master
      - docker_deploy:
          context: docker
          requires:
            - unit
            - integrate
          filters:
            branches:
              only: master
