"""The master list of IceCube institutions and their details.

More or less,
 a more structured JSON file (or less structured MongoDB)

NOTE: Keep things simple here. Avoid non-basic imports,

      so file can be imported by 3rd parties independently.
"""

INSTITUTIONS = {
    "Aachen": {
        "abbreviation": "RWTH",
        "has_mou": "true",
        "is_US": "false",
        "name": "RWTH Aachen University",
    },
    "AcademiaSinica": {
        "abbreviation": "AS",
        "has_mou": "true",
        "is_US": "false",
        "name": "Academia Sinica",
    },
    "Adelaide": {
        "abbreviation": "ADELAIDE",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Adelaide",
    },
    "Alabama": {
        "abbreviation": "UA",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Alabama",
    },
    "Alaska-Anchorage": {
        "abbreviation": "UAA",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Alaska Anchorage",
    },
    "Berlin": {
        "abbreviation": "HUMBOLDT",
        "has_mou": "true",
        "is_US": "false",
        "name": "Humboldt-Universität zu Berlin",
    },
    "Bochum": {
        "abbreviation": "BOCHUM",
        "has_mou": "true",
        "is_US": "false",
        "name": "Ruhr-Universität Bochum",
    },
    "Canterbury": {
        "abbreviation": "UC",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Canterbury",
    },
    "Chiba": {
        "abbreviation": "CHIBA",
        "has_mou": "true",
        "is_US": "false",
        "name": "Chiba University",
    },
    "Chicago": {
        "abbreviation": "UCHICAGO",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Chicago",
    },
    "Clark-Atlanta": {
        "abbreviation": "CAU",
        "has_mou": "true",
        "is_US": "true",
        "name": "Clark-Atlanta University",
    },
    "Columbia": {
        "abbreviation": "COLUMBIA",
        "has_mou": "true",
        "is_US": "true",
        "name": "Columbia University",
    },
    "Copenhagen": {
        "abbreviation": "NBI",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Copenhagen",
    },
    "Delaware": {
        "abbreviation": "UD",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Delaware",
    },
    "Drexel": {
        "abbreviation": "DREXEL",
        "has_mou": "true",
        "is_US": "true",
        "name": "Drexel University",
    },
    "Erlangen": {
        "abbreviation": "ERLANGEN",
        "has_mou": "true",
        "is_US": "false",
        "name": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
    },
    "GaTech": {
        "abbreviation": "GTECH",
        "has_mou": "true",
        "is_US": "true",
        "name": "Georgia Institute of Technology",
    },
    "Gent": {
        "abbreviation": "GENT",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Gent",
    },
    "Harvard": {
        "abbreviation": "HARVARD",
        "has_mou": "true",
        "is_US": "true",
        "name": "Harvard University",
    },
    "Kansas": {
        "abbreviation": "KU",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Kansas",
    },
    "Karlsruhe": {
        "abbreviation": "KIT",
        "has_mou": "true",
        "is_US": "false",
        "name": "Karlsruhe Institute of Technology",
    },
    "KingsCollege": {
        "abbreviation": "KCL",
        "has_mou": "true",
        "is_US": "false",
        "name": "King's College London",
    },
    "LBNL": {
        "abbreviation": "LBNL",
        "has_mou": "true",
        "is_US": "true",
        "name": "Lawrence Berkeley National Laboratory",
    },
    "Loyola": {
        "abbreviation": "LOYOLA",
        "has_mou": "true",
        "is_US": "true",
        "name": "Loyola University Chicago",
    },
    "Mainz": {
        "abbreviation": "MAINZ",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Mainz",
    },
    "Manchester": {
        "abbreviation": "UOM",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Manchester",
    },
    "Marquette": {
        "abbreviation": "MARQUETTE",
        "has_mou": "true",
        "is_US": "true",
        "name": "Marquette University",
    },
    "Maryland": {
        "abbreviation": "UMD",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Maryland",
    },
    "Mephi": {
        "abbreviation": "MEPHI",
        "has_mou": "true",
        "is_US": "false",
        "name": "Moscow Engineering Physics Institute",
    },
    "Mercer": {
        "abbreviation": "MERCER",
        "has_mou": "true",
        "is_US": "true",
        "name": "Mercer University",
    },
    "Michigan-State": {
        "abbreviation": "MSU",
        "has_mou": "true",
        "is_US": "true",
        "name": "Michigan State University",
    },
    "Munich": {
        "abbreviation": "TUM",
        "has_mou": "true",
        "is_US": "false",
        "name": "Technische Universität München",
    },
    "Munster": {
        "abbreviation": "MÜNSTER",
        "has_mou": "true",
        "is_US": "false",
        "name": "Universität Münster",
    },
    "Nebraska": {
        "abbreviation": "UNL",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Nebraska–Lincoln",
    },
    "NotreDame": {
        "abbreviation": "ND",
        "has_mou": "true",
        "is_US": "true",
        "name": "Notre Dame",
    },
    "Ohio-State": {
        "abbreviation": "OSU",
        "has_mou": "true",
        "is_US": "true",
        "name": "Ohio State University",
    },
    "Oxford": {
        "abbreviation": "UOX",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Oxford",
    },
    "Padova": {
        "abbreviation": "UNIPD",
        "has_mou": "true",
        "is_US": "false",
        "name": "Università Degli Studi di Padova",
    },
    "Penn-State": {
        "abbreviation": "PSU",
        "has_mou": "true",
        "is_US": "true",
        "name": "Pennsylvania State University",
    },
    "QMLondon": {
        "abbreviation": "QMLONDON",
        "has_mou": "true",
        "is_US": "false",
        "name": "Queen Mary University of London",
    },
    "Queens": {
        "abbreviation": "QUEEN'S",
        "has_mou": "true",
        "is_US": "false",
        "name": "Queen's University",
    },
    "Rochester": {
        "abbreviation": "ROCHESTER",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Rochester",
    },
    "SD-Mines-Tech": {
        "abbreviation": "SDSMT",
        "has_mou": "true",
        "is_US": "true",
        "name": "South Dakota School of Mines and Technology",
    },
    "Southern": {
        "abbreviation": "SUBR",
        "has_mou": "true",
        "is_US": "true",
        "name": "Southern University",
    },
    "Stockholm": {
        "abbreviation": "SU",
        "has_mou": "true",
        "is_US": "false",
        "name": "Stockholm University",
    },
    "Stony-Brook": {
        "abbreviation": "SBU",
        "has_mou": "true",
        "is_US": "true",
        "name": "Stony Brook University",
    },
    "Sungkyunkwan": {
        "abbreviation": "SKKU",
        "has_mou": "true",
        "is_US": "false",
        "name": "Sungkyunkwan University",
    },
    "Texas-Arlington": {
        "abbreviation": "UTA",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Texas at Arlington",
    },
    "UC-Irvine": {
        "abbreviation": "UCI",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of California, Irvine",
    },
    "UCLA": {
        "abbreviation": "UCLA",
        "has_mou": "true",
        "is_US": "true",
        "name": "UCLA",
    },
    "UCLouvain": {
        "abbreviation": "UCLOUVAIN",
        "has_mou": "true",
        "is_US": "false",
        "name": "Université catholique de Louvain",
    },
    "UW-Madison": {
        "abbreviation": "UW",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Wisconsin–Madison",
    },
    "UW-River-Falls": {
        "abbreviation": "UWRF",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Wisconsin, River Falls",
    },
    "Uppsala": {
        "abbreviation": "UU",
        "has_mou": "true",
        "is_US": "false",
        "name": "Uppsala University",
    },
    "Utah": {
        "abbreviation": "UTAH",
        "has_mou": "true",
        "is_US": "true",
        "name": "University of Utah",
    },
    "Wuppertal": {
        "abbreviation": "WUPPERTAL",
        "has_mou": "true",
        "is_US": "false",
        "name": "University of Wuppertal",
    },
    "Yale": {
        "abbreviation": "YALE",
        "has_mou": "true",
        "is_US": "true",
        "name": "Yale University",
    },
}
